apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vyc275gf7-dotnet-basic
  janus-idp.io/tekton: vyc275gf7-dotnet-basic
  backstage.io/kubernetes-id: vyc275gf7-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vyc275gf7-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
